apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: object-store-gateway
    app.kubernetes.io/instance: thanos-store-cluster3
    app.kubernetes.io/name: thanos-store
    app.kubernetes.io/version: v0.32.5
  name: thanos-store-cluster3
  namespace: thanos
spec:
  endpoints:
  - port: http
    relabelings:
    - action: replace
      separator: /
      sourceLabels:
      - namespace
      - pod
      targetLabel: instance
  selector:
    matchLabels:
      app.kubernetes.io/component: object-store-gateway
      app.kubernetes.io/instance: thanos-store-cluster3
      app.kubernetes.io/name: thanos-store
