prometheus:
  thanosService:
    enabled: true
  thanosServiceMonitor:
    enabled: true
  thanosServiceExternal:
    enabled: true
    type: LoadBalancer
    annotations:
      external-dns.alpha.kubernetes.io/hostname: thanos-sidecar-${CLUSTER_NAME_2}.${DOMAIN_NAME}
  prometheusSpec:
    thanos: 
      objectStorageConfig:
        existingSecret:
          name: thanos-s3-config-${CLUSTER_NAME_2}
          key: thanos-s3-config-${CLUSTER_NAME_2}
