apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: database-write-hashring
    app.kubernetes.io/instance: thanos-receive-cluster2
    app.kubernetes.io/name: thanos-receive
    app.kubernetes.io/version: v0.32.5
    controller.receive.thanos.io/hashring: cluster2
  name: thanos-receive-cluster2
  namespace: thanos
  annotations:
    external-dns.alpha.kubernetes.io/hostname: thanos-receive-cluster2.${DOMAIN_NAME}
spec:
  # clusterIP: None
  type: LoadBalancer
  ports:
  - name: grpc
    port: 10901
    targetPort: 10901
  - name: http
    port: 10902
    targetPort: 10902
  - name: remote-write
    port: 19291
    targetPort: 19291
  selector:
    app.kubernetes.io/component: database-write-hashring
    app.kubernetes.io/instance: thanos-receive-cluster2
    app.kubernetes.io/name: thanos-receive
    controller.receive.thanos.io/hashring: cluster2
