grafana:
  enabled: false
prometheus:
  prometheusSpec:
    replicas: 2
    retention: 4h
    retentionSize: "20GB"
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    topologySpreadConstraints: 
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: prometheus
    # additionalScrapeConfigsSecret: 
    #   enabled: true
    #   name: additional-scrape-configs
    #   key: avalanche-additional.yaml
    storageSpec: 
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
        selector: {}
    remoteWrite: 
    - url: http://thanos-receive-${CLUSTER_NAME_2}.${DOMAIN_NAME}:19291/api/v1/receive
    remoteWriteDashboards: true
    externalLabels: 
      cluster: "${CLUSTER_NAME_2}"
      cluster_name: "${CLUSTER_NAME_2}"
      origin_prometheus: "${CLUSTER_NAME_2}"
