prometheus:
  thanosService:
    enabled: true
  thanosServiceMonitor:
    enabled: true
  thanosServiceExternal:
    enabled: true
    type: LoadBalancer
  prometheusSpec:
    thanos: 
      objectStorageConfig:
        existingSecret:
          name: thanos-s3-config-ekscluster1
          key: thanos-s3-config-ekscluster1
