apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: database-write-hashring
    app.kubernetes.io/instance: thanos-receive-cluster3
    app.kubernetes.io/name: thanos-receive
    app.kubernetes.io/version: v0.32.5
    controller.receive.thanos.io/hashring: cluster3
  name: thanos-receive-cluster3
  namespace: thanos
spec:Í
  # clusterIP: None
  type: LoadBalancer
  annotations:
    external-dns.alpha.kubernetes.io/hostname: $(NAME).${DOMAIN_NAME}
  ports:
  - name: grpc
    port: 10901
    targetPort: 10901
  - name: http
    port: 10902
    targetPort: 10902
  - name: remote-write
    port: 19291
    targetPort: 19291
  selector:
    app.kubernetes.io/component: database-write-hashring
    app.kubernetes.io/instance: thanos-receive-cluster3
    app.kubernetes.io/name: thanos-receive
    controller.receive.thanos.io/hashring: cluster3
